favorites:
    base:
        path: http://127.0.0.1:8080/
    forgotpassword:
        url: http://127.0.0.1:8080/newPassword
    file:
        background-pic:  ${user.home}/favorites/backgroundpictures/
        profile-pic:  ${user.home}/favorites/profilepictures/
    static:
        url: /usr/local/static

spring:

    profiles:
        active: dev
    servlet:
        multipart:
            enabled: true
            max-file-size: 1000000
            max-request-size: 1000000

server:
    port: 8100
